<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="didragoescu" lastModifiedBy="didragoescu" checksumTest="true" creationDate="08/05/2014 15:52:02 +0300" engineType="DML" lastModifiedDate="08/05/2014 16:10:23 +0300" engineVersion="2.0">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/bdoc1.dmlflw"/>
   </mappingInformations>
</project>